<?php

__('Tools');
__('Furniture');
__('Garden');
__('Appliances');
__('Household');
__('Books, films & music');
__('Video Games');
__('Jewellery & accessories');
__('Bags & luggage');
__('Clothing & shoes – men');
__('Clothing & shoes – women');
__('Toys & games');
__('Baby & kids');
__('Pet supplies');
__('Health & beauty');
__('Mobile Phones');
__('Electronics & computers');
__('Car parts');
__('Bicycles');
__('Cars, vans & motorcycles');
__('Home & garden');
__('Property for sale');
__('Hobbies');
__('Antiques & collectibles');
__('Arts & crafts');
__('Garage sale');
__('Miscellaneous');
__('Musical Instruments');
__('Property to rent');
__('Sport & outdoors');
__('Housing');
__('Property for rent');
__('Entertainment');
__('Clothing & accessories');
__('Family');
__('Electronics');
__('Vehicles & bicycles');
__('Services');
__('a test category');
