<?php

__('List something');
__('Post an announcement');
__('property');
__('property_plural');
__('');
__('_plural');
__('Buy');
__('Sell something');
__('item');
__('item_plural');
__('');
__('_plural');
__('Book Room');
__('Rent room');
__('room');
__('room_plural');
__('night');
__('night_plural');
__('Book Session');
__('List your service');
__('place');
__('place_plural');
__('session');
__('session_plural');
__('Rent Item');
__('Rent an item');
__('item');
__('item_plural');
__('day');
__('day_plural');
__('Request');
__('Request');
__('');
__('_plural');
__('');
__('_plural');
